apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis-server
  namespace: planespotter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis-server
        tier: backend
    spec:
      containers:
      - name: redis-server
        # image: redis
        image: harbor.lab.local/planespotter/redis:v1
        ports:
        - containerPort: 6379
      - name: telegraf
        # image: puckpuck/wavefront-telegraf
        image: harbor.lab.local/planespotter/wavefront-telegraf:v1
        ports:
        - name: udp-statsd
          containerPort: 8125
        - name: udp-8092
          containerPort: 8092
        - name: tcp-8094
          containerPort: 8094
        env:
        - name: WAVEFRONT_PROXY
          value: wavefront-proxy.default
        - name: INTERVAL
          value: 20s
        - name: METRIC_SOURCE_NAME
          # This can be change to use the Deployment / Statefulset name instead as a simple value
          # The metric source name should not be an ephemeral value
          value: planespotter-redis
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: telegraf-d
          mountPath: /etc/telegraf/telegraf.d
      volumes:
      - name: telegraf-d
        projected:
          sources:
          - configMap:
              name: telegraf-redis-config 
---
apiVersion: v1
kind: Service
metadata:
  name: redis-server
  namespace: planespotter
  labels:
    app: redis-server
    tier: backend
spec:
  ports:
  - port: 6379
  selector:
    app: redis-server
    tier: backend
  clusterIP: None
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-redis-config
  namespace: planespotter
data:
  redis.conf: |
    [[inputs.redis]]
      ## specify servers via a url matching:
      ##  [protocol://][:password]@address[:port]
      ##  e.g.
      ##    tcp://localhost:6379
      ##    tcp://:password@192.168.99.100
      ##
      ## If no servers are specified, then localhost is used as the host.
      ## If no port is specified, 6379 is used
      servers = ["tcp://localhost:6379"]

      # Specify optional tags to be applied to all metrics for this plugin
      # NOTE: Order matters, this needs to be at the end of the plugin definition
      # [[inputs.redis.tags]]
        # tag1 = "foo"
        # tag2 = "bar"
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: adsb-sync
  namespace: planespotter
  labels:
    app: adsb-sync
    tier: data-sync
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adsb-sync
  template:
    metadata:
      labels:
        app: adsb-sync
    spec:
      containers:
      - name: adsb-sync
        # image: yfauser/adsb-sync:1d791ea6e96eb50adb15e773d1d783f511618c97
        image: harbor.lab.local/planespotter/adsb-sync:v1
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: config-volume
          mountPath: /usr/src/app/config
      volumes:
        - name: config-volume
          configMap:
            name: adsb-sync-cfg
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adsb-sync-cfg
  namespace: planespotter
data:
  config.ini: |
    [main]
    redis_server = redis-server
    adsb_server_poll_url = https://public-api.adsbexchange.com/VirtualRadar/AircraftList.json
    adsb_poll_filter = ?fRegS=N
    adsb_type = poll
