---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: planespotter-frontend
  namespace: planespotter
  labels:
    app: planespotter-frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: planespotter-frontend
  template:
    metadata:
      labels:
        app: planespotter-frontend
        tier: frontend
    spec:
      containers:
      - name: planespotter-frontend
        # image: nvpnathan/planespotter-frontend:v1
        image: harbor.lab.local/planespotter/frontend:v1 
        imagePullPolicy: Always
        env:
        - name: PLANESPOTTER_API_ENDPOINT
          value: planespotter-svc
      - name: telegraf
        # image: puckpuck/wavefront-telegraf
        image: harbor.lab.local/planespotter/wavefront-telegraf:v1
        ports:
        - name: udp-statsd
          containerPort: 8125
        - name: udp-8092
          containerPort: 8092
        - name: tcp-8094
          containerPort: 8094
        env:
        - name: WAVEFRONT_PROXY
          value: wavefront-proxy.default
        - name: INTERVAL
          value: 20s
        - name: METRIC_SOURCE_NAME
          # This can be change to use the Deployment / Statefulset name instead as a simple value
          # The metric source name should not be an ephemeral value
          value: planespotter-nginx
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        resources:
          requests:
            memory: 30Mi
            cpu: 100m
          limits:
            memory: 50Mi
            cpu: 200m
        volumeMounts:
        - name: telegraf-d
          mountPath: /etc/telegraf/telegraf.d
      volumes:
      - name: telegraf-d
        projected:
          sources:
          - configMap:
              name: telegraf-nginx-config 
---
apiVersion: v1
kind: Service
metadata:
  namespace: planespotter
  name: planespotter-frontend
  labels:
    app: planespotter-frontend
spec:
  ports:
    # the port that this service should serve on
    - port: 80
  selector:
    app: planespotter-frontend
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: planespotter-frontend
  namespace: planespotter
spec:
  rules:
  - host: planespotter.k8slabapps.lab.local
    http:
      paths:
      - backend:
          serviceName: planespotter-frontend
          servicePort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf-nginx-config
  namespace: planespotter
data:
  nginx.conf: |
    [[inputs.nginx]]
      ## An array of Nginx status URI to gather stats.
      urls = ["http://localhost/basic_status"]

      ## Optional SSL Config
      # ssl_ca = "/path/to/ca.pem"
      # ssl_cert = "/path/to/cert.pem"
      # ssl_key = "/path/to/key.pem"
      ## Use SSL but skip chain & host verification
      # insecure_skip_verify = false

      ## HTTP response timeout (default: 5s)
      response_timeout = "5s"

      # Specify optional tags to be applied to all metrics for this plugin
      # NOTE: Order matters, this needs to be at the end of the plugin definition
      # [[inputs.nginx.tags]]
        # tag1 = "foo"
        # tag2 = "bar"
